services:
    _defaults:
        autowire: true
        autoconfigure: true

    Bcs\IsotopeCumulativeFilterBundle\EventListener\GeneratePageListener: ~

    Bcs\IsotopeCumulativeFilterBundle\EventListener\InitializeRequestCacheListener: ~

    Bcs\IsotopeCumulativeFilterBundle\EventListener\ReplaceIsorcInRedirectListener: ~
